# https://docs.gitlab.com/ce/ci/yaml/

.build:
  script:
    - make info
    - make
    - make test-depend
    - make test

.build-linux:
  extends: [ .build ]
  tags: [ x64, linux, docker ]
  image:
    # For available go versions, check ci/docker/versions.md
    name: objectboxio/buildenv-generator-ubuntu:2025-10-16
    pull_policy: [if-not-present]

bt:linux-x64:go1.18:
  extends: [ .build-linux ]
  before_script:
    - export PATH=/usr/lib/go-1.18/bin:$PATH

bt:linux-x64:go-2nd-latest:
  extends: [ .build-linux ]
  before_script:
    - export PATH=/usr/local/go1.24.9/bin:$PATH

# Uses the latest go version (available in the Docker image)
bt:linux-x64:
  extends: [ .build-linux ]
  after_script:
    - zip objectbox-generator-Linux.zip objectbox-generator
  artifacts:
    expire_in: 1 day
    paths:
      - objectbox-generator-Linux.zip

bt:mac:
  extends: [ .build ]
  tags: [ mac, go, xcode ]
  after_script:
    - zip objectbox-generator-macOS.zip objectbox-generator
  artifacts:
    expire_in: 1 day
    paths:
      - objectbox-generator-macOS.zip

bt:win-x64:
  extends: [ .build ]
  tags: [ windows, go ]
  after_script:
    - zip objectbox-generator-Windows.zip objectbox-generator.exe
  artifacts:
    expire_in: 1 day
    paths:
      - objectbox-generator-Windows.zip
