package templates

import (
	"text/template"
)

var JsBindingTemplate = template.Must(template.New("binding-js").Funcs(funcMap).Parse(`
// Code generated by ObjectBox; DO NOT EDIT.

{{define "field-value"}}{{if .Optional}}*{{end}}object.{{.JsName}}{{end -}}

import * as fb from "flatbuffers";

{{range $entity := .Model.EntitiesWithMeta}}
export class {{ $entity.Name }} {
	static id = {{ $entity.Id.GetId }};
	static uid = {{ $entity.Id.GetUid }}n;

	/**
	 * Encode the given {{ $entity.Name }} object into a Uint8Array (flatbuffers -formatted).
	 */
	static toFlatbuffers(fbb, object) {
		fbb.clear();

		{{ range $property := $entity.Properties -}}
			{{- $code := CreateOffsetProperty $property  }}
			{{- if $code }}
		{{ $code }}
			{{- end}}
		{{- end }}

		fbb.startObject({{ len $entity.Properties }});
		{{- range $property := $entity.Properties }}
			{{- if $property.Meta.Optional}}
				if (object.{{$property.Meta.JsName}})
			{{- end }}
			{{- if CreateOffsetProperty $property }}
		{{ AddFieldOffset $property }}
			{{- else }}
				{{- if and $.NaNAsNull $property.Meta.FbIsFloatingPoint }}
					if (!std::isnan({{ template "field-value" $property.Meta }}))
				{{- end }}
		{{ AddField $property -}}
			{{- end }}
		{{- end }}
		fbb.finish(fbb.endObject());
		return fbb.asUint8Array();
	}

	/**
	 * Decode the given Uint8Array (flatbuffers -formatted) to a {{ $entity.Name }} object.
	 */
	static fromFlatbuffers(bytes, outObject = null) {
		let bb = new fb.ByteBuffer(
			// This copy is necessary to avoid:
			// (...) The provided ArrayBufferView value must not be shared
			new Uint8Array(bytes)
		);
		let bbPos = bb.readInt32(bb.position()) + bb.position();

		{{- range $property := $entity.Properties }}
		{{ WriteGetAssignOffset $property }}
		{{- end }}

		if (outObject == null) outObject = {};
		{{- range $property := $entity.Properties }}
		{{ ReadProperty $property }}
		{{- end }}
		return outObject;
	}
}
{{end}}
`))
