package templates

import (
	"text/template"
)

var JsBindingTemplate = template.Must(template.New("binding-js").Funcs(funcMap).Parse(`
// Code generated by ObjectBox; DO NOT EDIT.

{{define "field-value"}}{{if .Optional}}*{{end}}object.{{.JsName}}{{end -}}
{{define "field-value-assign-pre"}}{{if IsOptionalPtr .Optional}}.reset(new {{.JsType}}({{else}} = {{end}}{{end -}}
{{define "field-value-assign-post"}}{{if IsOptionalPtr .Optional}})){{end}}{{end -}}

import * as fb from "flatbuffers";

{{range $entity := .Model.EntitiesWithMeta}}
class {{ $entity.Meta.JsName}} {
	static toFlatbuffers(fbb, object) {
		fbb.clear();
		{{/* Offset */}}
		{{- range $property := $entity.Properties}}
		{{ $code := $property.Meta.FbOffsetAssignment }}
		{{- if $code}}{{$code}}{{- end}}
		{{- end}}

		flatbuffers::uoffset_t fbStart = fbb.startObject( /* numfields */);
		{{range $property := $entity.Properties}}
			{{- if $property.Meta.Optional}}if (object.{{$property.Meta.JsName}}){{end}}
			{{- if $property.Meta.FbOffsetAssignment}}fbb.AddOffset({{$property.FbvTableOffset}}, offset{{$property.Meta.JsName}});
			{{- else -}}
				{{- if and $.NaNAsNull $property.Meta.FbIsFloatingPoint -}}
					if (!std::isnan({{ template "field-value" $property.Meta }}))
				{{end -}}
				fbb.AddElement({{$property.FbvTableOffset}}, {{ template "field-value" $property.Meta}}
				{{if eq "bool" $property.Meta.JsType}} ? 1 : 0{{end}});
			{{- end}}
		{{end -}}
		flatbuffers::Offset<flatbuffers::Table> offset;
		offset.o = fbb.EndTable(fbStart);
		fbb.Finish(offset);
	}

	static fromFlatbuffer(uint8Array) {
		let bb = new fb.ByteBuffer(uint8Array);

		const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
		assert(table);
		{{- range $property := $entity.Properties}}
			{{- if eq "std::string" $property.Meta.JsType}}
		{
			auto* ptr = table->GetPointer<const flatbuffers::String*>({{$property.FbvTableOffset}});
			if (ptr) {
				outObject.{{$property.Meta.JsName}}
					{{- if $property.Meta.Optional}}
						{{- if IsOptionalPtr $.Optional -}}
							.reset(new std::string(ptr->c_str(), ptr->size()));
						{{- else -}}
							.emplace(ptr->c_str(), ptr->size());
						{{- end}}
					{{- else -}}
						.assign(ptr->c_str(), ptr->size());
					{{- end}}
			} else {
				outObject.{{$property.Meta.JsName}}
				{{- if $property.Meta.Optional -}}
					.reset();
				{{- else -}}
					.clear();
				{{- end}}
			}
		}
			{{- else if eq "std::vector<std::string>" $property.Meta.JsType}}
		{
			auto* ptr = table->GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>*>({{$property.FbvTableOffset}});
			if (ptr) {
				{{- if $property.Meta.Optional}}
				outObject.{{$property.Meta.JsName}}{{if IsOptionalPtr $property.Meta.Optional}}.reset(new {{$property.Meta.JsType}}({{else}} = {{$property.Meta.JsType}}(){{end}}{{template "field-value-assign-post" $property.Meta}};
				{{- end}}
				outObject.{{$property.Meta.JsName}}.reserve(ptr->size());
				for (flatbuffers::uoffset_t i = 0; i < ptr->size(); i++) {
					auto* itemPtr = ptr->Get(i);
					if (itemPtr) outObject.{{$property.Meta.JsName}}.emplace_back(itemPtr->c_str());
				}
			} else {
				outObject.{{$property.Meta.JsName}}
				{{- if $property.Meta.Optional -}}
					.reset();
				{{- else -}}
					.clear();
				{{- end}}
			}
		}
			{{- else if $property.Meta.FbIsVector}}
		{
			auto* ptr = table->GetPointer<const {{$property.Meta.FbOffsetType}}*>({{$property.FbvTableOffset}});
			if (ptr) { 
				outObject.{{$property.Meta.JsName}}
				{{- if IsOptionalPtr $property.Meta.Optional}}{{template "field-value-assign-pre" $property.Meta}}ptr->begin(), ptr->end(){{template "field-value-assign-post" $property.Meta}}
				{{- else if $property.Meta.Optional}} = {{$property.Meta.JsType}}(ptr->begin(), ptr->end())
				{{- else}}.assign(ptr->begin(), ptr->end())
				{{- end}};
			} else {
				outObject.{{$property.Meta.JsName}}
				{{- if $property.Meta.Optional -}}
					.reset();
				{{- else -}}
					.clear();
				{{- end}}
			}
		}
			{{- else }}
		{{			if $property.Meta.Optional -}}
		if (table->CheckField({{$property.FbvTableOffset}})) {{end -}} 
		outObject.{{$property.Meta.JsName}}
				{{- template "field-value-assign-pre" $property.Meta -}}
			table->GetField<{{$property.Meta.JsFbType}}>({{- $property.FbvTableOffset}}, {{$property.Meta.FbDefaultValue}}){{if eq "bool" $property.Meta.JsType}} != 0{{end}}
				{{- template "field-value-assign-post" $property.Meta}};
				{{- if $property.Meta.Optional}} else outObject.{{$property.Meta.JsName}}.reset();{{- end}}
			{{- end }}
		{{- end}}
	}
}
{{end}}
`))
