/*
 * ObjectBox Generator - a build time tool for ObjectBox
 * Copyright (C) 2018-2024 ObjectBox Ltd. All rights reserved.
 * https://objectbox.io
 *
 * This file is part of ObjectBox Generator.
 *
 * ObjectBox Generator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * ObjectBox Generator is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with ObjectBox Generator.  If not, see <http://www.gnu.org/licenses/>.
 */

package templates

import (
	"text/template"
)

// JsModelTemplate is used to generate the model initialization code
var JsModelTemplate = template.Must(template.New("model-js").Funcs(funcMap).Parse(`
// Code generated by ObjectBox; DO NOT EDIT.

import { 
    wasm,
    OBXEntityFlags,
    OBXPropertyFlags,
    OBXPropertyType
} from "#objectbox/js/wasm.js";

/**
 * Initialize an ObjectBox model for all entities.
 * The returned value is a Number representing a handle to the model.
 * You will likely want to pass it to the Store (through StoreOptions), once the store is opened it MUST NOT be freed manually.
 */
export function createModel() {
    let model = wasm.obx_model();
	{{range $entity := .Model.Entities}}
	wasm.obx_model_entity(model, "{{$entity.Name}}", {{$entity.Id.GetId}}, {{$entity.Id.GetUid}}n);
	{{- with $entity.Flags}}
	wasm.obx_model_entity_flags(model, {{CoreEntityFlags .}});
	{{- end -}}
	{{range $property := $entity.Properties}}
	wasm.obx_model_property(model, "{{$property.Name}}", OBXPropertyType.{{PropTypeName $property.Type}}, {{$property.Id.GetId}}, {{$property.Id.GetUid}}n);
	{{- with $property.Flags}}
	wasm.obx_model_property_flags(model, {{CorePropFlags .}});
	{{- end -}}
	{{- if $property.HnswParams -}}
	{{- if $property.HnswParams.Dimensions}}
	wasm.obx_model_property_index_hnsw_dimensions(model, {{$property.HnswParams.Dimensions}});
	{{- end -}}
	{{- if $property.HnswParams.DistanceType}}
	wasm.obx_model_property_index_hnsw_distance_type(model, OBXVectorDistanceType_{{ $property.HnswParams.DistanceType }});
	{{- end -}}
	{{- if $property.HnswParams.NeighborsPerNode}}
	wasm.obx_model_property_index_hnsw_neighbors_per_node(model, {{ $property.HnswParams.NeighborsPerNode }});
	{{- end -}}
	{{- if $property.HnswParams.IndexingSearchCount}}
	wasm.obx_model_property_index_hnsw_indexing_search_count(model, {{ $property.HnswParams.IndexingSearchCount }});
	{{- end -}}
	{{- if $property.HnswParams.ReparationBacklinkProbability}}
	wasm.obx_model_property_index_hnsw_reparation_backlink_probability(model, {{ $property.HnswParams.ReparationBacklinkProbability }});
	{{- end -}}
	{{- if $property.HnswParams.VectorCacheHintSizeKb}}
	wasm.obx_model_property_index_hnsw_vector_cache_hint_size_kb(model, {{ $property.HnswParams.VectorCacheHintSizeKb }});
	{{- end -}}
	{{- if $property.HnswParams.Flags}}
	{{- with $property.HnswParams.Flags}}
	wasm.obx_model_property_index_hnsw_flags(model, {{CoreHnswFlags .}});
	{{- end -}}
	{{- end -}}
	{{- end -}}
	{{- if $property.RelationTarget}}
	wasm.obx_model_property_relation(model, "{{$property.RelationTarget}}", {{$property.IndexId.GetId}}, {{$property.IndexId.GetUid}}n);
	{{- else if $property.IndexId}}
	wasm.obx_model_property_index_id(model, {{$property.IndexId.GetId}}, {{$property.IndexId.GetUid}}n);
	{{- end -}}
	{{- end}}
	{{range $relation := $entity.Relations -}}
    wasm.obx_model_relation(model, {{$relation.Id.GetId}}, {{$relation.Id.GetUid}}n, {{$relation.Target.Id.GetId}}, {{$relation.Target.Id.GetUid}}n);
	{{end -}}
	wasm.obx_model_entity_last_property_id(model, {{$entity.LastPropertyId.GetId}}, {{$entity.LastPropertyId.GetUid}}n);
	{{end}}
	wasm.obx_model_last_entity_id(model, {{.Model.LastEntityId.GetId}}, {{.Model.LastEntityId.GetUid}}n);
	{{- if .Model.LastIndexId}}
	wasm.obx_model_last_index_id(model, {{.Model.LastIndexId.GetId}}, {{.Model.LastIndexId.GetUid}}n);
	{{- end}}
	{{- if .Model.LastRelationId}}
	wasm.obx_model_last_relation_id(model, {{.Model.LastRelationId.GetId}}, {{.Model.LastRelationId.GetUid}}n);
	{{- end}}
	return model;
}
`))
