// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package reflection

import "strconv"

/// New schema language features that are not supported by old code generators.
type AdvancedFeatures uint64

const (
	AdvancedFeaturesAdvancedArrayFeatures    AdvancedFeatures = 1
	AdvancedFeaturesAdvancedUnionFeatures    AdvancedFeatures = 2
	AdvancedFeaturesOptionalScalars          AdvancedFeatures = 4
	AdvancedFeaturesDefaultVectorsAndStrings AdvancedFeatures = 8
)

var EnumNamesAdvancedFeatures = map[AdvancedFeatures]string{
	AdvancedFeaturesAdvancedArrayFeatures:    "AdvancedArrayFeatures",
	AdvancedFeaturesAdvancedUnionFeatures:    "AdvancedUnionFeatures",
	AdvancedFeaturesOptionalScalars:          "OptionalScalars",
	AdvancedFeaturesDefaultVectorsAndStrings: "DefaultVectorsAndStrings",
}

var EnumValuesAdvancedFeatures = map[string]AdvancedFeatures{
	"AdvancedArrayFeatures":    AdvancedFeaturesAdvancedArrayFeatures,
	"AdvancedUnionFeatures":    AdvancedFeaturesAdvancedUnionFeatures,
	"OptionalScalars":          AdvancedFeaturesOptionalScalars,
	"DefaultVectorsAndStrings": AdvancedFeaturesDefaultVectorsAndStrings,
}

func (v AdvancedFeatures) String() string {
	if s, ok := EnumNamesAdvancedFeatures[v]; ok {
		return s
	}
	return "AdvancedFeatures(" + strconv.FormatInt(int64(v), 10) + ")"
}
