// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package reflection

import "strconv"

type BaseType int8

const (
	BaseTypeNone        BaseType = 0
	BaseTypeUType       BaseType = 1
	BaseTypeBool        BaseType = 2
	BaseTypeByte        BaseType = 3
	BaseTypeUByte       BaseType = 4
	BaseTypeShort       BaseType = 5
	BaseTypeUShort      BaseType = 6
	BaseTypeInt         BaseType = 7
	BaseTypeUInt        BaseType = 8
	BaseTypeLong        BaseType = 9
	BaseTypeULong       BaseType = 10
	BaseTypeFloat       BaseType = 11
	BaseTypeDouble      BaseType = 12
	BaseTypeString      BaseType = 13
	BaseTypeVector      BaseType = 14
	BaseTypeObj         BaseType = 15
	BaseTypeUnion       BaseType = 16
	BaseTypeArray       BaseType = 17
	BaseTypeVector64    BaseType = 18
	BaseTypeMaxBaseType BaseType = 19
)

var EnumNamesBaseType = map[BaseType]string{
	BaseTypeNone:        "None",
	BaseTypeUType:       "UType",
	BaseTypeBool:        "Bool",
	BaseTypeByte:        "Byte",
	BaseTypeUByte:       "UByte",
	BaseTypeShort:       "Short",
	BaseTypeUShort:      "UShort",
	BaseTypeInt:         "Int",
	BaseTypeUInt:        "UInt",
	BaseTypeLong:        "Long",
	BaseTypeULong:       "ULong",
	BaseTypeFloat:       "Float",
	BaseTypeDouble:      "Double",
	BaseTypeString:      "String",
	BaseTypeVector:      "Vector",
	BaseTypeObj:         "Obj",
	BaseTypeUnion:       "Union",
	BaseTypeArray:       "Array",
	BaseTypeVector64:    "Vector64",
	BaseTypeMaxBaseType: "MaxBaseType",
}

var EnumValuesBaseType = map[string]BaseType{
	"None":        BaseTypeNone,
	"UType":       BaseTypeUType,
	"Bool":        BaseTypeBool,
	"Byte":        BaseTypeByte,
	"UByte":       BaseTypeUByte,
	"Short":       BaseTypeShort,
	"UShort":      BaseTypeUShort,
	"Int":         BaseTypeInt,
	"UInt":        BaseTypeUInt,
	"Long":        BaseTypeLong,
	"ULong":       BaseTypeULong,
	"Float":       BaseTypeFloat,
	"Double":      BaseTypeDouble,
	"String":      BaseTypeString,
	"Vector":      BaseTypeVector,
	"Obj":         BaseTypeObj,
	"Union":       BaseTypeUnion,
	"Array":       BaseTypeArray,
	"Vector64":    BaseTypeVector64,
	"MaxBaseType": BaseTypeMaxBaseType,
}

func (v BaseType) String() string {
	if s, ok := EnumNamesBaseType[v]; ok {
		return s
	}
	return "BaseType(" + strconv.FormatInt(int64(v), 10) + ")"
}
