/*
 * Copyright (C) 2020 ObjectBox Ltd. All rights reserved.
 * https://objectbox.io
 *
 * This file is part of ObjectBox Generator.
 *
 * ObjectBox Generator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * ObjectBox Generator is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ObjectBox Generator.  If not, see <http://www.gnu.org/licenses/>.
 */

// Package generator provides tools to generate ObjectBox entity bindings between GO structs & ObjectBox schema
package generator

import (
	"fmt"
	"io/ioutil"
	"math/rand"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/objectbox/objectbox-generator/internal/generator/model"
)

// Version specifies the current generator version.
const Version = "0.9.1"

// VersionId specifies the current generator version identifier.
// It is used to validate generated code compatibility and is increased when there are changes in the generated code.
// Internal generator changes that don't change the output do not cause an increase.
const VersionId = 6

// ModelInfoFile returns the model info JSON file name in the given directory
func ModelInfoFile(dir string) string {
	return filepath.Join(dir, "objectbox-model.json")
}

// CodeGenerator interface is used to abstract per-language generators, e.g. for Go, C, C++, etc
type CodeGenerator interface {
	// BindingFile returns a name of the binding file for the given entity file.
	BindingFile(forFile string) string

	// ModelFile returns the model GO file for the given JSON info file path
	ModelFile(forFile string) string

	// IsGeneratedFile returns true if the given path is recognized as a file generated by this generator
	IsGeneratedFile(file string) bool

	// ParseSource reads the source file and creates a model representation
	ParseSource(sourceFile string) (*model.ModelInfo, error)

	// WriteBindingFiles generates and writes binding source code files
	WriteBindingFiles(sourceFile string, options Options, mergedModel *model.ModelInfo) error

	// WriteBindingFiles generates and writes binding source code file for model setup
	WriteModelBindingFile(options Options, mergedModel *model.ModelInfo) error
}

// WriteFile writes data to targetFile, while using permissions either from the targetFile or permSource
func WriteFile(file string, data []byte, permSource string) error {
	var perm os.FileMode
	// copy permissions either from the existing file or from the source file
	if info, _ := os.Stat(file); info != nil {
		perm = info.Mode()
	} else if info, err := os.Stat(permSource); info != nil {
		perm = info.Mode()
	} else {
		return err
	}

	return ioutil.WriteFile(file, data, perm)
}

// Process is the main API method of the package
// it takes source file & model-information file paths and generates bindings (as a sibling file to the source file)
func Process(sourceFile string, options Options) error {
	var err error

	// if no random generator is provided, we create and seed a new one
	if options.Rand == nil {
		options.Rand = rand.New(rand.NewSource(time.Now().UTC().UnixNano()))
	}

	if len(options.ModelInfoFile) == 0 {
		options.ModelInfoFile = ModelInfoFile(filepath.Dir(sourceFile))
	}

	var modelInfo *model.ModelInfo

	modelInfo, err = model.LoadOrCreateModel(options.ModelInfoFile)
	if err != nil {
		return fmt.Errorf("can't init ModelInfo: %s", err)
	}

	modelInfo.Rand = options.Rand
	defer modelInfo.Close()

	if err = modelInfo.Validate(); err != nil {
		return fmt.Errorf("invalid ModelInfo loaded: %s", err)
	}

	// if the model is valid, upgrade it to the latest version
	modelInfo.MinimumParserVersion = model.ModelVersion
	modelInfo.ModelVersion = model.ModelVersion

	if err = createBinding(options, sourceFile, modelInfo); err != nil {
		return err
	}

	if err = createModel(options, modelInfo); err != nil {
		return err
	}

	return nil
}

func createBinding(options Options, sourceFile string, storedModel *model.ModelInfo) error {
	currentModel, err := options.CodeGenerator.ParseSource(sourceFile)
	if err != nil {
		return err
	}

	if err = mergeBindingWithModelInfo(currentModel, storedModel); err != nil {
		return fmt.Errorf("can't merge model information: %s", err)
	}

	// TODO check relation cycles for Go, not other languages
	// if err = storedModel.CheckRelationCycles(); err != nil {
	// 	return err
	// }

	if err = storedModel.Finalize(); err != nil {
		return fmt.Errorf("model finalization failed: %s", err)
	}

	return options.CodeGenerator.WriteBindingFiles(sourceFile, options, storedModel)
}

func createModel(options Options, modelInfo *model.ModelInfo) error {
	if err := modelInfo.Write(); err != nil {
		return fmt.Errorf("can't write model-info file %s: %s", options.ModelInfoFile, err)
	}

	return options.CodeGenerator.WriteModelBindingFile(options, modelInfo)
}

const recursionSuffix = "/..."

// Clean removes generated files in the given path.
// Removes *.obx.go and objectbox-model.go but keeps objectbox-model.json
func Clean(codeGenerator CodeGenerator, path string) error {
	var recursive bool

	// if it's a pattern
	if strings.HasSuffix(path, recursionSuffix) {
		recursive = true
		path = path[0:len(path)-len(recursionSuffix)] + "/*"
	} else {
		// if it's a directory
		if finfo, err := os.Stat(path); err == nil && finfo.IsDir() {
			path = path + "/*"
		}
	}

	matches, err := filepath.Glob(path)
	if err != nil {
		return err
	}

	for _, subpath := range matches {
		finfo, err := os.Stat(subpath)
		if err != nil {
			return err
		}

		if recursive && finfo.Mode().IsDir() {
			err = Clean(codeGenerator, subpath+recursionSuffix)
		} else if finfo.Mode().IsRegular() && codeGenerator.IsGeneratedFile(subpath) {
			fmt.Printf("Removing %s\n", subpath)
			err = os.Remove(subpath)
		}

		if err != nil {
			return err
		}
	}

	return nil
}
